name: weather
description: "An example project to give weather to any device."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  location: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
