name: weather
description: "An example project to give weather to any device."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3
  flutter: 3.24.3

dependencies:
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  geocoding: ^3.0.0
  get_it: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  json_annotation: ^4.9.0
  location: ^7.0.0
  logger: ^2.4.0
  retrofit: ^4.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  hive_generator: ^2.0.1
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  retrofit_generator: ^9.1.2
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
